// Frontend-only stock images - no database needed
export interface StockImage {
  id: string
  name: string
  url: string
  category: "business" | "technology" | "team" | "charts" | "abstract"
  tags: string[]
  is_premium: boolean
}

export const STOCK_IMAGES: StockImage[] = [
  // ==================== BUSINESS (15 images) ====================
  {
    id: "biz-1",
    name: "Executive Boardroom",
    url: "/modern-executive-boardroom-meeting-corporate-profe.jpg",
    category: "business",
    tags: ["meeting", "corporate", "boardroom", "executives"],
    is_premium: false,
  },
  {
    id: "biz-2",
    name: "Modern Office Space",
    url: "/modern-open-office-space-with-glass-walls-natural-.jpg",
    category: "business",
    tags: ["office", "workspace", "modern", "interior"],
    is_premium: false,
  },
  {
    id: "biz-3",
    name: "Business Handshake",
    url: "/professional-business-handshake-deal-partnership-a.jpg",
    category: "business",
    tags: ["deal", "partnership", "handshake", "agreement"],
    is_premium: false,
  },
  {
    id: "biz-4",
    name: "Strategy Planning",
    url: "/business-strategy-planning-session-whiteboard-stic.jpg",
    category: "business",
    tags: ["strategy", "planning", "brainstorming"],
    is_premium: true,
  },
  {
    id: "biz-5",
    name: "Corporate Presentation",
    url: "/professional-giving-presentation-large-screen-audi.jpg",
    category: "business",
    tags: ["presentation", "speaker", "conference"],
    is_premium: false,
  },
  {
    id: "biz-6",
    name: "Startup Office",
    url: "/trendy-startup-office-exposed-brick-modern-furnitu.jpg",
    category: "business",
    tags: ["startup", "modern", "creative"],
    is_premium: false,
  },
  {
    id: "biz-7",
    name: "Contract Signing",
    url: "/signing-business-contract-document-pen-professiona.jpg",
    category: "business",
    tags: ["contract", "signing", "legal", "agreement"],
    is_premium: true,
  },
  {
    id: "biz-8",
    name: "City Skyline Office",
    url: "/corner-office-city-skyline-view-sunset-professiona.jpg",
    category: "business",
    tags: ["office", "skyline", "view", "executive"],
    is_premium: true,
  },
  {
    id: "biz-9",
    name: "Client Meeting",
    url: "/business-professionals-meeting-client-laptop-docum.jpg",
    category: "business",
    tags: ["meeting", "client", "discussion"],
    is_premium: false,
  },
  {
    id: "biz-10",
    name: "Financial Review",
    url: "/financial-analysts-reviewing-reports-charts-docume.jpg",
    category: "business",
    tags: ["finance", "analysis", "reports"],
    is_premium: false,
  },
  {
    id: "biz-11",
    name: "Global Business",
    url: "/global-business-world-map-connections-internationa.jpg",
    category: "business",
    tags: ["global", "international", "worldwide"],
    is_premium: true,
  },
  {
    id: "biz-12",
    name: "Investment Meeting",
    url: "/investor-meeting-startup-pitch-presentation-ventur.jpg",
    category: "business",
    tags: ["investment", "pitch", "venture capital"],
    is_premium: true,
  },
  {
    id: "biz-13",
    name: "Success Celebration",
    url: "/business-team-celebrating-success-achievement-high.jpg",
    category: "business",
    tags: ["success", "celebration", "team", "achievement"],
    is_premium: false,
  },
  {
    id: "biz-14",
    name: "Professional Workshop",
    url: "/professional-workshop-training-session-interactive.jpg",
    category: "business",
    tags: ["workshop", "training", "learning"],
    is_premium: false,
  },
  {
    id: "biz-15",
    name: "Corporate Headquarters",
    url: "/modern-corporate-headquarters-building-glass-facad.jpg",
    category: "business",
    tags: ["headquarters", "building", "architecture"],
    is_premium: true,
  },

  // ==================== TECHNOLOGY (12 images) ====================
  {
    id: "tech-1",
    name: "Code Development",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["code", "programming", "developer", "software"],
    is_premium: false,
  },
  {
    id: "tech-2",
    name: "Data Center",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["server", "infrastructure", "data center"],
    is_premium: false,
  },
  {
    id: "tech-3",
    name: "AI Neural Network",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["AI", "machine learning", "neural network"],
    is_premium: true,
  },
  {
    id: "tech-4",
    name: "Cloud Computing",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["cloud", "computing", "saas"],
    is_premium: false,
  },
  {
    id: "tech-5",
    name: "Cybersecurity Shield",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["security", "protection", "cyber"],
    is_premium: true,
  },
  {
    id: "tech-6",
    name: "Mobile App Development",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["mobile", "app", "development", "UI"],
    is_premium: false,
  },
  {
    id: "tech-7",
    name: "Blockchain Network",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["blockchain", "crypto", "distributed"],
    is_premium: true,
  },
  {
    id: "tech-8",
    name: "IoT Devices",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["IoT", "smart devices", "automation"],
    is_premium: false,
  },
  {
    id: "tech-9",
    name: "API Integration",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["API", "integration", "services"],
    is_premium: false,
  },
  {
    id: "tech-10",
    name: "Virtual Reality",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["VR", "virtual reality", "immersive"],
    is_premium: true,
  },
  {
    id: "tech-11",
    name: "Tech Workspace",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["workspace", "desk", "tech"],
    is_premium: false,
  },
  {
    id: "tech-12",
    name: "Quantum Computing",
    url: "/placeholder.svg?height=400&width=600",
    category: "technology",
    tags: ["quantum", "computing", "advanced"],
    is_premium: true,
  },

  // ==================== TEAM (10 images) ====================
  {
    id: "team-1",
    name: "Diverse Team Portrait",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["team", "diversity", "portrait", "professional"],
    is_premium: false,
  },
  {
    id: "team-2",
    name: "Team Collaboration",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["collaboration", "teamwork", "planning"],
    is_premium: false,
  },
  {
    id: "team-3",
    name: "Remote Team Call",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["remote", "video call", "virtual"],
    is_premium: false,
  },
  {
    id: "team-4",
    name: "Executive Leadership",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["leadership", "executives", "management"],
    is_premium: true,
  },
  {
    id: "team-5",
    name: "Team Celebration",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["celebration", "success", "party"],
    is_premium: false,
  },
  {
    id: "team-6",
    name: "Engineering Team",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["engineering", "developers", "tech team"],
    is_premium: false,
  },
  {
    id: "team-7",
    name: "Creative Team",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["creative", "design", "brainstorming"],
    is_premium: false,
  },
  {
    id: "team-8",
    name: "Sales Team",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["sales", "business development"],
    is_premium: true,
  },
  {
    id: "team-9",
    name: "Mentorship Session",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["mentorship", "coaching", "learning"],
    is_premium: false,
  },
  {
    id: "team-10",
    name: "Startup Founders",
    url: "/placeholder.svg?height=400&width=600",
    category: "team",
    tags: ["founders", "startup", "entrepreneurs"],
    is_premium: true,
  },

  // ==================== CHARTS (10 images) ====================
  {
    id: "chart-1",
    name: "Revenue Growth Chart",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["growth", "revenue", "chart", "trend"],
    is_premium: false,
  },
  {
    id: "chart-2",
    name: "Market Share Pie",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["pie chart", "market share", "analytics"],
    is_premium: false,
  },
  {
    id: "chart-3",
    name: "KPI Dashboard",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["dashboard", "KPI", "analytics", "metrics"],
    is_premium: true,
  },
  {
    id: "chart-4",
    name: "Market Trends Analysis",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["market", "trends", "analysis"],
    is_premium: false,
  },
  {
    id: "chart-5",
    name: "Financial Report Charts",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["financial", "report", "quarterly"],
    is_premium: true,
  },
  {
    id: "chart-6",
    name: "Sales Funnel",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["sales", "funnel", "conversion"],
    is_premium: false,
  },
  {
    id: "chart-7",
    name: "User Analytics",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["user", "analytics", "engagement"],
    is_premium: false,
  },
  {
    id: "chart-8",
    name: "Competitive Benchmark",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["benchmark", "competitive", "comparison"],
    is_premium: true,
  },
  {
    id: "chart-9",
    name: "ROI Calculator",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["ROI", "investment", "returns"],
    is_premium: false,
  },
  {
    id: "chart-10",
    name: "Product Metrics",
    url: "/placeholder.svg?height=400&width=600",
    category: "charts",
    tags: ["product", "metrics", "usage"],
    is_premium: true,
  },

  // ==================== ABSTRACT (8 images) ====================
  {
    id: "abs-1",
    name: "Blue Gradient Wave",
    url: "/placeholder.svg?height=400&width=600",
    category: "abstract",
    tags: ["gradient", "wave", "blue", "modern"],
    is_premium: false,
  },
  {
    id: "abs-2",
    name: "Geometric Pattern",
    url: "/placeholder.svg?height=400&width=600",
    category: "abstract",
    tags: ["geometric", "pattern", "shapes"],
    is_premium: false,
  },
  {
    id: "abs-3",
    name: "Digital Network Lines",
    url: "/placeholder.svg?height=400&width=600",
    category: "abstract",
    tags: ["network", "digital", "connections"],
    is_premium: false,
  },
  {
    id: "abs-4",
    name: "Minimalist Lines",
    url: "/placeholder.svg?height=400&width=600",
    category: "abstract",
    tags: ["minimalist", "lines", "clean"],
    is_premium: false,
  },
  {
    id: "abs-5",
    name: "Futuristic Grid",
    url: "/placeholder.svg?height=400&width=600",
    category: "abstract",
    tags: ["futuristic", "grid", "neon"],
    is_premium: true,
  },
  {
    id: "abs-6",
    name: "Gradient Mesh",
    url: "/placeholder.svg?height=400&width=600",
    category: "abstract",
    tags: ["gradient", "mesh", "colorful"],
    is_premium: false,
  },
  {
    id: "abs-7",
    name: "Data Visualization Art",
    url: "/placeholder.svg?height=400&width=600",
    category: "abstract",
    tags: ["data", "visualization", "particles"],
    is_premium: true,
  },
  {
    id: "abs-8",
    name: "Light Rays",
    url: "/placeholder.svg?height=400&width=600",
    category: "abstract",
    tags: ["light", "rays", "dramatic"],
    is_premium: false,
  },
]

// Helper to filter images by category
export function getImagesByCategory(category?: string): StockImage[] {
  if (!category || category === "all") return STOCK_IMAGES
  return STOCK_IMAGES.filter((img) => img.category === category)
}

// Helper to search images
export function searchImages(query: string): StockImage[] {
  const lowerQuery = query.toLowerCase()
  return STOCK_IMAGES.filter(
    (img) =>
      img.name.toLowerCase().includes(lowerQuery) || img.tags.some((tag) => tag.toLowerCase().includes(lowerQuery)),
  )
}
